import { MenuItem } from '@/types';

export const MENU: MenuItem[] = [
  {
    id: 'hangsang',
    name: '항상',
    price: 4000,
    description: '항상 입안을 가득 채우는 풍부한 초콜릿 향미',
    category: '커피',
    availableOptions: ['hot', 'ice'],
    image: '/menu-hangsang.jpg',
    tags: ['초콜릿', '고소한', '달콤한'],
    beanBrand: 'Black Suit',
    origins: [
      { name: '브라질', ratio: '60%', type: '생산국' },
      { name: '콜롬비아', ratio: '25%', type: '생산국' },
      { name: '에티오피아', ratio: '15%', type: '생산국' },
    ],
    cupNotes: '초콜릿, 로스팅 너트, 단맛의 여운',
    intro: '누구나 편하게 마실 수 있는 커피를 추구합니다. 초콜릿의 달콤함과 구운 견과의 고소함이 조화롭고, 단맛의 여운이 길게 이어집니다.',
  },
  {
    id: 'pureun',
    name: '푸른',
    price: 4000,
    description: '싱그러운 시트러스 과일, 은은한 꽃 향',
    category: '커피',
    availableOptions: ['hot', 'ice'],
    image: '/menu-pureun.jpg',
    tags: ['복숭아', '상큼한', '플로럴'],
    beanBrand: 'Velvet White',
    origins: [
      { name: '비산 디모', ratio: '40%', type: '농장', region: '에티오피아 구지' },
      { name: '합타무 이르가체페 단체', ratio: '30%', type: '협동조합', region: '에티오피아 이르가체페' },
      { name: '합타무 이르가체페 고티티', ratio: '30%', type: '농장', region: '에티오피아 이르가체페' },
    ],
    cupNotes: '복숭아, 오렌지, 재스민, 홍차, 브라운 슈거',
    intro: '복숭아, 오렌지, 재스민처럼 싱그럽고 홍차, 브라운 슈거 같은 긴 여운이 매력적인 커피입니다. 3가지 에티오피아 원두로 구성되어 기분 좋은 향과 맛을 즐길 수 있습니다.',
  },
  {
    id: 'namu',
    name: '나무',
    price: 3500,
    description: '블루레몬에이드 · 아이스 단일',
    category: '논커피',
    availableOptions: ['ice'],
    image: '/menu-namu.jpg',
    tags: ['레몬', '청량한', '논커피'],
    intro: '블루큐라소와 레몬의 조합으로 시원하고 청량한 한 잔. 눈도 즐겁고 입도 즐거운 여름 음료입니다.',
  },
];
